from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ApplicationBuilder, CommandHandler, CallbackQueryHandler, ContextTypes

TOKEN = "8600274020:AAFljWxGl4B5kVsH65puKjpsDGWyM3H0Rik"

# MENU PRINCIPAL
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    keyboard = [
            [InlineKeyboardButton("🛒 Boutique", callback_data="shop")]
                ]
                    reply_markup = InlineKeyboardMarkup(keyboard)

                        await update.message.reply_text(
                                "🔥 Bienvenue sur *Frezz Shop* 🔥\n\nClique sur le bouton pour voir la boutique 👇",
                                        parse_mode="Markdown",
                                                reply_markup=reply_markup
                                                    )

                                                    # GESTION DES BOUTONS
                                                    async def button(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                        query = update.callback_query
                                                            await query.answer()

                                                                # MENU SHOP
                                                                    if query.data == "shop":
                                                                            keyboard = [
                                                                                        [InlineKeyboardButton("💎 Server Boosts", callback_data="boosts")],
                                                                                                    [InlineKeyboardButton("👻 Snap+ Premium", callback_data="snap")]
                                                                                                            ]
                                                                                                                    await query.edit_message_text(
                                                                                                                                "🛒 *Boutique Frezz Shop*",
                                                                                                                                            parse_mode="Markdown",
                                                                                                                                                        reply_markup=InlineKeyboardMarkup(keyboard)
                                                                                                                                                                )

                                                                                                                                                                    # BOOSTS
                                                                                                                                                                        elif query.data == "boosts":
                                                                                                                                                                                keyboard = [
                                                                                                                                                                                            [InlineKeyboardButton("x14 Boosts • 1 mois", callback_data="b1")],
                                                                                                                                                                                                        [InlineKeyboardButton("x14 Boosts • 3 mois", callback_data="b2")],
                                                                                                                                                                                                                ]
                                                                                                                                                                                                                        await query.edit_message_text(
                                                                                                                                                                                                                                    "💎 *Server Boosts*",
                                                                                                                                                                                                                                                parse_mode="Markdown",
                                                                                                                                                                                                                                                            reply_markup=InlineKeyboardMarkup(keyboard)
                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                        # SNAP
                                                                                                                                                                                                                                                                            elif query.data == "snap":
                                                                                                                                                                                                                                                                                    keyboard = [
                                                                                                                                                                                                                                                                                                [InlineKeyboardButton("3 mois", callback_data="s1")],
                                                                                                                                                                                                                                                                                                            [InlineKeyboardButton("6 mois", callback_data="s2")],
                                                                                                                                                                                                                                                                                                                        [InlineKeyboardButton("12 mois", callback_data="s3")],
                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                        await query.edit_message_text(
                                                                                                                                                                                                                                                                                                                                                    "👻 *Snap+ Premium*",
                                                                                                                                                                                                                                                                                                                                                                parse_mode="Markdown",
                                                                                                                                                                                                                                                                                                                                                                            reply_markup=InlineKeyboardMarkup(keyboard)
                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                        # PRODUITS
                                                                                                                                                                                                                                                                                                                                                                                            elif query.data == "b1":
                                                                                                                                                                                                                                                                                                                                                                                                    await product(query, "x14 Boosts • 1 mois", "4.50€")
                                                                                                                                                                                                                                                                                                                                                                                                        elif query.data == "b2":
                                                                                                                                                                                                                                                                                                                                                                                                                await product(query, "x14 Boosts • 3 mois", "8.50€")
                                                                                                                                                                                                                                                                                                                                                                                                                    elif query.data == "s1":
                                                                                                                                                                                                                                                                                                                                                                                                                            await product(query, "Snap+ 3 mois", "3.65€")
                                                                                                                                                                                                                                                                                                                                                                                                                                elif query.data == "s2":
                                                                                                                                                                                                                                                                                                                                                                                                                                        await product(query, "Snap+ 6 mois", "5.99€")
                                                                                                                                                                                                                                                                                                                                                                                                                                            elif query.data == "s3":
                                                                                                                                                                                                                                                                                                                                                                                                                                                    await product(query, "Snap+ 12 mois", "17.15€")

                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ACHAT
                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif query.data.startswith("buy"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await query.edit_message_text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "💳 *Paiement*\n\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "• PayPal\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "• Virement bancaire\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "• Crypto (LTC)\n\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "📩 Contacte-moi pour acheter : @Frezzhot",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            parse_mode="Markdown"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # FONCTION PRODUIT
                                                                                                 
